services:
  faculty-recommender:
    build:
      context: ..
      dockerfile: DS614-Faculty-Recommender/Dockerfile
    container_name: faculty-app
    ports:
      - "8001:8001" # FastAPI backend
      - "8501:8501" # Streamlit frontend
    restart: unless-stopped
    volumes:
      - ./:/app
